DROP TABLE IF EXISTS ITEM;
CREATE TABLE ITEM (
  id VARCHAR(30) PRIMARY KEY,
  name VARCHAR(100) NOT NULL
);

INSERT INTO ITEM(id, name) VALUES('0', 'item 1');
INSERT INTO ITEM(id, name) VALUES('1', 'item 2');

